name: matrix fruit
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    matrix_fruits:
      strategy:
        fail-fast: true
        matrix:
          fruits: [pomme, poire, banane, pÃªche]
          nom: [paul, pierre, jack]
    steps:
      - name: Affiche le fruit et le nom
        run: echo "le fruit est ${{ matrix.fruits }} et le nom est ${{ matrix.nom }}"
  