name: liste de fruits
on:
  push:
    branches: [ main ]

jobs:
  liste_de_fruits:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        fruits: [pomme, poire, banane, pÃªche]
        nom: [paul, pierre, jack]
    steps:
      - name: Affiche le fruit et le nom
        run: echo "le fruit est ${{ matrix.fruits }} et le nom est ${{ matrix.nom }}"
  