name: download artifacts
on: workflow_dispatch
jobs:
  uploads:
    runs-on: ubuntu-latest
    steps:
      - name: create file
      # chemin here or in path
        run: echo "Something" > artifact.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt
          
  download:
    runs-on: ubuntu-latest
    needs: uploads
    steps:
      - name: download artifact
      # chemin here or in path
        run: echo "Something" > artifact.txt
      - name: upload artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: read-file
      # cat linux affiche le contenu d'un fichier
        run: cat artifact.txt
