name: workflow_run_done
on:
  workflow_run:
    workflows: [worflows for issues]
    types: 
      - completed
env:
  WORKFLOW_RUN_DONE: "le workflow worflows for issues est terminé"
jobs:
  workflow_run_done:
    runs-on: ubuntu-latest
    steps:
      - name: le workflow worflows for issues est terminé
        run: echo "$WORKFLOW_RUN_DONE"